org: nichollasf
app: lambda-serverless-framework
service: lambda-serverless-framework

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  
  # consumer:
  #   handler: handler.consumer
  #   events:
  #     - msk:
  #         arn: arn:aws:kafka:us-east-1:111111111:cluster/ClusterName/a1a1a1a1a
  #         topic: kafkaTopic
  #         saslScram512: arn:aws:secretsmanager:region:XXXXXX:secret:AmazonMSK_xxxxxx

  # producer:
  #   handler: handler.producer
  #   events:
  #     - msk:
  #         bootstrapServers:
  #           - abc3.xyz.com:9092
  #           - abc2.xyz.com:9092
  #         topic: MySelfManagedKafkaTopic
